# product_management_service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-processing-service
  template:
    metadata:
      labels:
        app: order-processing-service
    spec:
      containers:
      - name: order-processing-service
        image: fakertaker/order-processing-service:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: order-processing-service
spec:
  type: LoadBalancer
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 30002
  selector:
    app: order-processing-service
